language: node_js
node_js:
- v6
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
script:
  - npm test -- -i --coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
  - CXX=g++-4.8
  - SENDGRID_KEY=sendgridKey
  - MASTER_KEY=masterKey
  - JWT_SECRET=jwtSecret
  - FLICKR_KEY=flickrKey
  - WATSON_KEY=watsonKey
  - FB_APP_SECRET=fbAppSecret
  - FB_APP_SECRET_DEV=fbAppSecretDev
